apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubegpt.fullname" . }}
  labels:
    {{- include "kubegpt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}81
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubegpt.selectorLabels" . | nindent 4 }}
