# permissions for end users to view kubegpts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kubegpt-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebilder-test
    app.kubernetes.io/part-of: kubebilder-test
    app.kubernetes.io/managed-by: kustomize
  name: kubegpt-viewer-role
rules:
- apiGroups:
  - core.kubegpt.io
  resources:
  - kubegpts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kubegpt.io
  resources:
  - kubegpts/status
  verbs:
  - get
